config/routes.rb
Rails.application.routes.draw do
  root 'routes#index'
  resources :routes do
    collection do
      get :index
      post :start
      get :bus_arrivals_ajax
    end
  end
  resources :search, only: [:index]
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :steps
  accepts_nested_attributes_for :steps, allow_destroy: true
  scope :time_desc, ->{order(created_at: :desc)}
  MINUTE = 60

  self.inheritance_column = nil
  enum type: {
    recent: 1,
    saved: 2
  }

  def duration
    steps.map{|s| s.body["duration"]["value"]}.inject(&:+).to_f / MINUTE
  end

  def eta
    Time.now() + duration.minutes
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route_history, only: [:index]
  before_action :set_steps, :set_weather, only: [:show]

  def index
  end

  def show
    @header = "Live Directions"
  end

  def start
    cached_route = Rails.cache.read(params["route"]["id"])
    @route = Route.new(route_params cached_route)
    if @route.save
      redirect_to @route
    else
      redirect_to action: "index"
    end
  end

  private
  def route_params route
    {
      origin_name: "Current Location",
      origin_address: route["legs"].first["start_address"],
      destination_name: route["destination"],
      destination_address: route["legs"].first["end_address"],
      type: Route.types[:recent],
      steps_attributes: route["legs"].first["steps"].map do |s|
        {content: s.to_json}
      end
    }
  end

  def set_steps
    @route = Route.find params[:id]
    @steps = []
    @route.steps.each do |s|
      if s.travel_mode == Step::TRAVEL_MODE_TRANSIT
        @steps << setup_waiting_step(s)
        if s.by_bus?
          org = BusStop.find_nearest(
            s.start_location["lat"], s.start_location["lng"])
          dest = BusStop.find_nearest(
            s.end_location["lat"], s.end_location["lng"])
          content = JSON.parse(s.content)
          content["bus_stops"] = BusRoute.available_routes(org, dest)
          s.content = content.to_json
        end
      end
      @steps << s
    end
  end

  def setup_waiting_step step
    content = {
      travel_mode: Step::TRAVEL_MODE_WALKING,
      start_location: step.start_location,
      end_location: step.start_location, #same as start
      vehicle: step.vehicle,
      departure: step.transit_details["departure_stop"]["name"]
    }
    if step.by_bus?
      origin = BusStop.find_nearest(
        step.start_location["lat"], step.start_location["lng"])
      dest = BusStop.find_nearest(
        step.end_location["lat"], step.end_location["lng"])
      services = BusRoute.available_services(origin, dest)
      content[:bus_stop_code] = origin.code
      content[:bus_stop_services] =
        BusStopApi.get_arrival_times(origin.code).select do |service|
          services.include? service["ServiceNo"]
        end
    end
    Step.new(route: step.route, content: content.to_json)
  end

  def set_route_history
    @route_history = Route.time_desc.recent.first(5)
  end

  def set_weather
    sl = @steps.first.start_location
    @weather = Weather.new(sl["lat"], sl["lng"]).get_latest
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
  class << self
    MINUTE = 60

    def to_weather_icon weather
      case weather.to_s
      when ""                 then ""
      when "Fair"             then "A"
      when "Partly Cloudy"    then "C"
      when "Cloudy"           then "D"
      when "Mist"             then "N"
      when "Showers"          then "R"
      when "Heavy Showers"    then "S"
      when "Thundery Showers" then "U"
      when "Heavy Thundery Showers" then "V"
      when "Light Rain"       then "X"
      when "Windy"            then "a"
      else "A"
      end
    end

    def min_to_arrival arrival_time
      return 0 if arrival_time.empty?
      [((Time.parse(arrival_time) - Time.now) / MINUTE).round(0), 0].max
    end
  end
end

app/views/routes/_bus-arrivals.html.erb
<% services.each do |service| %>
<tr class="bus-arrivals">
<td>
  <span>Bus <%= service["ServiceNo"] %></span>
</td><td>
  <p class="min"><%= RoutesHelper.min_to_arrival service["NextBus"]["EstimatedArrival"] %></p>
  <% next_arrivals = [service["NextBus2"]["EstimatedArrival"], service["NextBus3"]["EstimatedArrival"]].select(&:present?).map{|a| RoutesHelper.min_to_arrival(a)}.join(", ") %>
  <small class="ml-2"><%= next_arrivals %></small>
</td></tr>
<% end %>

app/views/routes/_camera.html.erb
<form id="control"></form>
<div>
  <video id="video" />
</div>
<span id="result"></span>
<script>
  var video = document.getElementById("video");
  var control = document.getElementById("control");

  getVideoSources(function(cam) {
    console.log("cam", cam);
    var b = document.createElement("input");
    b.type = "button";
    b.className = "btn btn-outline-primary btn-sm";
    b.value = "Scan QR Code";
    b.onclick = getMain(cam.id);
    control.appendChild(b);
    console.log('add button');
  });

  function getMain(cam_id) {
    return function() {
      main(cam_id);
    };
  }

  function main(cam_id) {
    navigator.getUserMedia({
      audio: false,
      video: {
        optional: [
          { sourceId: cam_id}
        ]
      }
    }, function(stream) { // success
      console.log("Start Video", stream);
      localStream = stream;
      video.src = URL.createObjectURL(stream);
      video.play();
      video.volume = 0;
      var stop = startReadQR(video, function(obj){
        stop();
        success(obj);
      }, function() {} );
    }, function(e) { // error
      console.error("Error on start video: " + e.code);
    });
  };

  function success(obj){
    console.log("Success", obj);
    result.innerText = JSON.stringify(obj);
  }

  function startReadQR(video, callback, error){
    var store = {
        all_length: 0,
        length: 0
    };
  
    var state = "run";
  
    qrcode.callback = function(res) {
      if(res == 'error decoding QR Code'){
        error();
      } else {
        console.log("read", res);
        //receiveQr(res, store, callback);
        callback(res);
      }
    }
    var videoRead = function() {
      var w = video.videoWidth;
      var h = video.videoHeight;
      var canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      var ctx = canvas.getContext("2d");
  
      var draw = function(){
        if(state == "stop"){
          return;
        }
  
        requestAnimationFrame(draw);
        ctx.drawImage(video, 0, 0, w, h);
        var img = canvas.toDataURL("image/png");
        qrcode.decode(img);
      };
  
      draw();
    }
  
    if (video.readyState == 0) {
      video.onloadedmetadata = videoRead;
    } else {
      videoRead();
    }
  
    return function(){
      state = "stop";
    };
  }
</script>

app/views/routes/_map-scripts.html.erb
<script type="text/javascript">
  var marker;
  var gmaps = {};

  function initMap() {
    var origin = [<%= step.start_location["lat"] %>, <%= step.start_location["lng"] %>];
    var destination = [<%= step.end_location["lat"] %>, <%= step.end_location["lng"] %>];
    var travelMode = "<%= step.travel_mode %>";

    gmaps.directionsService = new google.maps.DirectionsService;
    gmaps.directionsDisplay = new google.maps.DirectionsRenderer;
    gmaps.map = new google.maps.Map(document.getElementById("map"), {
      maxZoom: 20,
      zoom: 15,
      center: {
        lat: origin[0],
        lng: origin[1]
      }
    });
    gmaps.directionsDisplay.setMap(gmaps.map);
    calculateAndDisplayRoute(origin, destination, travelMode);
    setMarker(origin);
    setInterval("updateCurrentLocation()", 3 * 1000);
  }

  function calculateAndDisplayRoute(origin, destination, travelMode, transitOptions = {}) {
    gmaps.directionsService.route({
      origin: {
        lat: origin[0],
        lng: origin[1]
      },
      destination: {
        lat: destination[0],
        lng: destination[1]
      },
      travelMode: travelMode,
      transitOptions: transitOptions
    }, function(response, status) {
      if (status === 'OK') {
        gmaps.directionsDisplay.setDirections(response);
      } else {
        window.alert('Directions request failed due to ' + status);
      }
    });
  }

  function setMarker(position){
    marker = new google.maps.Marker({
      position: {
        lat: position[0],
        lng: position[1]
      },
      zIndex: 99,
      map: gmaps.map,
      icon: "<%= image_path("bluedot.png") %>"
    });
    marker.setMap(gmaps.map);
  }

  function clearMarker(){
    marker.setMap(null);
  }

  function updateCurrentLocation() {
    getPosition().then(function(position){
      clearMarker();
      setMarker(position);
      remindArrival(position);
    });
  }

  var currentRoute = {};
  var showRemind = false;
  function remindArrival(position) {
    var NEAR = 0.0030;
    var travelMode = currentRoute["travel_mode"];
    if(travelMode !== "TRANSIT" || showRemind) {
      return;
    }
    if(distance(position[0], position[1]) < NEAR){
      showRemind = true;
      var stop = currentRoute.transit_details.arrival_stop.name;
      alert("Alight at next stop - " + stop);
    }
  }

  function distance(lat, lng) {
    return Math.sqrt(
      (currentRoute["end_location"]["lat"] - lat) ** 2 +
      (currentRoute["end_location"]["lng"] - lng) ** 2
    );
  }

  function updateRoute(next = true) {
    var currentIndex = parseInt($(".carousel-item.active").attr("data-route-index"));
    var targetIndex = next ? currentIndex + 1 : currentIndex - 1;
    if(targetIndex < 0 || targetIndex > <%= @steps.count - 1 %>) {
      return;
    }
    currentRoute = JSON.parse($(`[data-route-index="${targetIndex}"]`).attr("data-route"));
    var travelMode = currentRoute["travel_mode"];
    var transitOptions = {};
    if(travelMode === "TRANSIT") {
      transitOptions["modes"] = [currentRoute["transit_details"]["line"]["vehicle"]["type"]];
    }
    calculateAndDisplayRoute(
      [currentRoute["start_location"]["lat"], currentRoute["start_location"]["lng"]],
      [currentRoute["end_location"]["lat"], currentRoute["end_location"]["lng"]],
      travelMode,
      transitOptions
    );
    showRemind = false;
  }
</script>
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>

app/views/routes/index.html.erb
<%= form_tag('/search', class: "my-3", method: "get") do %>
  <div class="form-inline">
    <%= text_field_tag "destination", "", class: "form-control mr-2 col", placeholder: "Where do you want to go?" %>
    <%= hidden_field_tag "lat", "", class: "form-control" %>
    <%= hidden_field_tag "lng", "", class: "form-control" %>
    <button id="submit" type="submit" class="btn btn-outline-dark" disabled>
      <i class="fa fa-search my-0 ml-auto" aria-hidden="true"></i>
    </button>
  </div>
<% end %>

<table class="table">
  <thead class="thead-default">
    <tr><th>Saved Routes</th></tr>
  </thead>
  <tbody>
    <tr><td>
      <span>Great World City</span>
      <small class="form-text text-muted">1 Kim Seng Promenade, Singapore 237994</small>
    </td></tr>
  </tbody>
</table>
<table class="table route-history">
  <thead class="thead-default">
    <tr><th>Recent Journeys</th></tr>
  </thead>
  <tbody>
  <% if @route_history.empty? %>
    <tr><td>
      <span>No Journey</span>
    </td></tr>
  <% else %>
    <% @route_history.each do |route| %>
      <tr><td>
        <a href="<%= route_path(route) %>" class="cell">
        <span><%= route.destination_name %></span>
        <small class="form-text text-muted"><%= route.destination_address %></small>
        </a>
      </td></tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<script>
$(document).ready(function(){
  getPosition().then(function(position){
    if(position !== undefined){
      document.getElementById("lat").value = position[0];
      document.getElementById("lng").value = position[1];
      $("#submit").prop("disabled", false);
    }
  }).catch(function(error){
    console.log(error);
  });
});
</script>

app/views/routes/show.html.erb
<div id="map" style="width:100%; height:500px"></div>

<div id="routesCarousel" class="carousel slide mb-5" data-ride="carousel" data-interval="false" data-wrap="false">
  <ol class="carousel-indicators carousel-indicators--round fixed-bottom">
<% @steps.each_with_index do |step, idx| %>
<% active = idx === 0 ? "active" : "" %>
    <li data-target="#routesCarousel" data-slide-to="<%= idx %>" class="<%= active %>"></li>
<% end %>
  </ol>

  <div class="carousel-inner">
<% @steps.each_with_index do |step, idx| %>
<% active = idx === 0 ? "active" : "" %>
<div class="carousel-item <%= active %>" data-route-index="<%= idx %>" data-route="<%= step.content %>">
<table class="table">
  <tbody>
    <% if step.body["departure"].present? %>
      <tr><td>
        <small class="form-text text-muted">Wait <%= step.body["vehicle"] %> at</small>
        <span><%= step.body["departure"] %></span>
      </td></tr>
      <% if step.body["vehicle"] == "Bus" && step.body["bus_stop_services"] %>
        <%= render partial: "bus-arrivals", locals: {services: step.body["bus_stop_services"]} %>
      <% end %>
    <% else %>
      <tr><td>
        <small class="form-text text-muted"><%= step.travel_mode %></small>
        <span><%= step.html_instructions %></span>
        <small class="form-text text-muted"><%= step.distance + " " + step.duration %></small>
      </td></tr>
      <% if step.transit? && step.by_bus? && step.body["bus_stops"] %>
      <tr class="bus-stops"><td>
        <ul class="list-group">
        <% step.body["bus_stops"].first.each do |bs| %>
        <li class="list-group-item">
          <i class="fa fa-circle-thin mr-3" aria-hidden="true"></i>
          <small class="bus-stop"><%= bs["name"] %></small>
        </li>
        <% end %>
        </ul>
      </td></tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>
<% end %>
  </div>

  <div class="fixed-bottom">
  <a class="carousel-control-prev" href="#routesCarousel" role="button" data-slide="prev" onClick="updateRoute(false)">
    <i class="fa fa-lg fa-angle-left" aria-hidden="true"></i>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#routesCarousel" role="button" data-slide="next" onClick="updateRoute(true)">
    <i class="fa fa-lg fa-angle-right" aria-hidden="true"></i>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>

<%= render partial: "map-scripts", locals: {step: @steps.first} %>